Separate Concepts: Factor 2 (Dependencies)
twelve-factor/twelve-factor pull request #14
Opened 2024-11-28 18:11 UTC by wycats

Updates the dependencies factor to separate concepts, examples and guidance.

2024-12-11 17:59 UTC, vishvananda requested changes
Some minor fixes inline

2024-12-11 17:59 UTC, vishvananda commented on content/dependencies.md
> +It declares all dependencies, completely and exactly, via a dependency declaration manifest. Furthermore, it uses a dependency isolation tool during execution to ensure that no implicit dependencies
can we turn these smart quotes back into regular quotes?

2024-12-11 17:59 UTC, vishvananda commented on content/dependencies.md
> -**A twelve-factor app never relies on implicit existence of system-wide packages.**  It declares all dependencies, completely and exactly, via a *dependency declaration* manifest.  Furthermore, it us
I note that this one specifically called out a *dependency declaration* manifest. Do we want to call out the manifest in the new version?

2024-12-11 17:59 UTC, vishvananda commented on content/dependencies.md
> +For example, Bundler for Ruby offers the Gemfile manifest format for dependency declaration and bundle exec for dependency isolation. In Python there are two separate tools for these steps – Pip is u
The "For example," interjection seems redundant with the "Examples" header. We can probably omit it.

2024-12-31 01:21 UTC, JonnyBnice84 approved these changes

2025-01-10 18:33 UTC, wycats commented on content/dependencies.md
> +It declares all dependencies, completely and exactly, via a dependency declaration manifest. Furthermore, it uses a dependency isolation tool during execution to ensure that no implicit dependencies
Those probably came from copy-pasting from Google Docs. On it.

2025-01-10 18:34 UTC, wycats commented on content/dependencies.md
> -**A twelve-factor app never relies on implicit existence of system-wide packages.**  It declares all dependencies, completely and exactly, via a *dependency declaration* manifest.  Furthermore, it us
The changes have this under the new section 2:

> It declares all dependencies, completely and exactly, via a dependency declaration manifest.

Does that work?

2025-01-16 22:45 UTC, vishvananda approved these changes

2025-01-16 22:54 UTC, merged

2026-09-17 05:41 UTC, InfinityFreakUniverseBoy approved these changes